// esteidpluginie.idl : IDL source for esteid-plugin-ie
//

// This file will be processed by the MIDL tool to
// produce the type library (esteidpluginie.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4E59E13F-7CEE-4013-9275-685FAFCD560B),
	dual,
	nonextensible,
	helpstring("IEstEIDIEPluginBHO Interface"),
	pointer_default(unique)
]
interface IEstEIDIEPluginBHO : IDispatch{
	[propget, id(1), helpstring("property version")] HRESULT version([out, retval] BSTR *result);
	[propget, id(2), helpstring("property errorMessage")] HRESULT errorMessage([out, retval] BSTR *result);
	[propget, id(3), helpstring("property errorCode")] HRESULT errorCode([out, retval] BSTR *result);
	[propget, id(4), helpstring("property language")] HRESULT pluginLanguage([out, retval] BSTR *result);
	[propput, id(4), helpstring("property language")] HRESULT pluginLanguage([in] BSTR language);
	[id(6), helpstring("method getCertificate()")] HRESULT getCertificate([out, retval] IDispatch **_certificate);
	[id(7), helpstring("method sign()")] HRESULT sign([in] BSTR id, [in] BSTR hash, [in] BSTR language, [out, retval] BSTR *signature); 
};
[
	object,
	uuid(E23AF8B5-2D34-45EC-95E6-24791F84486E),
	dual,
	nonextensible,
	helpstring("IEstEIDCertificate Interface"),
	pointer_default(unique)
]
interface IEstEIDCertificate : IDispatch{
	[propget, id(1), helpstring("property certificate id")] HRESULT id([out, retval] BSTR *id);
	[propget, id(2), helpstring("property certificate certificateAsHex")] HRESULT certificateAsHex([out, retval] BSTR *certificate);
	[propget, id(3), helpstring("property certificate cert (certificateAsHex)")] HRESULT cert([out, retval] BSTR *certificate);
};
[
	uuid(23EF5046-6402-4C39-B34B-3C47826805D1),
	version(1.0),
	helpstring("esteidpluginie 1.0 Type Library")
]
library esteidpluginieLib
{
	importlib("stdole2.tlb");
	[
		uuid(2A4E94A4-B275-491A-9E32-CD7A26FC7C3B),
		helpstring("EstEIDIEPluginBHO Class")
	]
	coclass EstEIDIEPluginBHO
	{
		[default] interface IEstEIDIEPluginBHO;
	};
	[
		uuid(2615B13B-A08B-442C-8032-4D9981060190),
		helpstring("EstEIDCertificate Class")
	]
	coclass EstEIDCertificate
	{
		[default] interface IEstEIDCertificate;
	};
};
